name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=false -p:PublishSingleFile=true
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Tool
        path: /home/runner/work/Wfrp4core-trans/Wfrp4core-trans/bin/Release/net5.0/win-x64/publish/*
